# Generated by Django 4.2.6 on 2023-12-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusniessCards',
            fields=[
                ('cardId', models.AutoField(primary_key=True, serialize=False)),
                ('fullName', models.CharField(max_length=100)),
                ('emailAddress', models.CharField(max_length=50)),
                ('contactNumber', models.CharField(max_length=50)),
                ('companyName', models.TextField(null=True)),
                ('address', models.TextField(null=True)),
                ('jobTitle', models.CharField(max_length=100)),
                ('exchangers', models.TextField(default='')),
            ],
        ),
    ]
